spring:
  datasource:
    username: root
    password: 401321
    url: jdbc:mysql://localhost:3306/store?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lgm.store.entitly
  configuration:
    map-underscore-to-camel-case: true

user:
  address:
    max-count: 20
